//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeusEstudos
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoa
    {
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<int> idade { get; set; }
        public string foto { get; set; }
        public byte[] foto2 { get; set; }
    }
}
