//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreinoLinq
{
    using System;
    using System.Collections.Generic;
    
    public partial class faixa
    {
        public int codigo_musica { get; set; }
        public int codigo_cd { get; set; }
        public Nullable<int> numero_faixa { get; set; }
    
        public virtual cd cd { get; set; }
        public virtual musica musica { get; set; }
    }
}
