//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreinoLinq
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gravadoraEntities : DbContext
    {
        public gravadoraEntities()
            : base("name=gravadoraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autor> autor { get; set; }
        public virtual DbSet<cd> cd { get; set; }
        public virtual DbSet<faixa> faixa { get; set; }
        public virtual DbSet<gravadora> gravadora { get; set; }
        public virtual DbSet<musica> musica { get; set; }
    }
}
